### ISSUE TITLE
Favicon.ico does not exist

### ISSUE THREAD

**Issue by travisdmathis** [Iverum/json-api-server#1]
When creating a test server with the supplied code returns the following error.

ERROR { ResourceNotFoundError: /favicon.ico does not exist
    at Router.find (/Users/travismathis/Projects/company-projects/status-mock-api/node_modules/restify/lib/router.js:613:14)
    at Server._route (/Users/travismathis/Projects/company-projects/status-mock-api/node_modules/restify/lib/server.js:753:21)
    at routeAndRun (/Users/travismathis/Projects/company-projects/status-mock-api/node_modules/restify/lib/server.js:711:14)
    at Server._handle (/Users/travismathis/Projects/company-projects/status-mock-api/node_modules/restify/lib/server.js:731:9)
    at Server.onRequest (/Users/travismathis/Projects/company-projects/status-mock-api/node_modules/restify/lib/server.js:332:14)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
  jse_shortmsg: '/favicon.ico does not exist',
  jse_info: {},
  message: '/favicon.ico does not exist',
  statusCode: 404,
  body: 
   { code: 'ResourceNotFound',
     message: '/favicon.ico does not exist' },
  restCode: 'ResourceNotFound' }

**Comment by Iverum** [comment]
Will be resolved (in a less than ideal way) with [this commit](https://github.com/Iverum/json-api-server/commit/f56cf53c4395942f5d93a9d099a411a9894c279d). I'll provide a better solution later.
